### ISSUE TITLE
Run error if import from from src/index in App.vue

### ISSUE THREAD

**Issue by mationai** [C451/trading-vue-101#10]
Want to import from src so I can understand the trading-vue code.

Chaning the import to:
`import TradingVue from 'trading-vue-js/src/index'`
gives:

```
ERROR in ./node_modules/trading-vue-js/src/TradingVue.vue 2:0
Module parse failed: Unexpected token (2:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
> <template>
```

How do I change the setup to run from src?

**Comment by C451** [comment]
A good levels of npm, js & vue.js is required to use the lib. At least at the current state. I'd recommend to start with the basics first, otherwise there will be a lot of questions like this. 

Hopefully, in 2021 I'll make the barrier lower.

**Comment by mationai** [comment]
The issue was node_modules was excluded from vue-loader. Fixed by copying trading-vue-js to src. In the process, found minor bug in trading-vue-js. PR'd.

**Comment by C451** [comment]
Nice
Oh yeah https://github.com/tvjsx/trading-vue-js/blob/vue3/src/components/Spinner.vue, vue3 was angry on this one.
